version: "3"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: sqlite
    volumes:
      - sqlite_data:/var/lib/sqlite

volumes:
  sqlite_data:
    driver: local